'use strict';
// Generated by scripts/build_bank_lump.js. Do not hand edit.
(function exposeBankLumpIdentity(root) {
    const identity = Object.freeze({
  "dot_name": "Bank",
  "issue_n": 1,
  "token": "5382e0e2",
  "binary_hash": "6985e92299b1c9828a7f0633fd4ddab74b9d356be0568ae4bc36aba0d5594982",
  "identity_hash": "3b19718e37c1f36fcca3457e3016ec722737bd33103fac22f1c616de0fd63b11",
  "self_gt": 186216846,
  "ns_slot": null,
  "ns_slot_policy": "dynamic",
  "boot_resident": false,
  "runtime_binding": {
    "registry_index": 54,
    "dispatch": "SystemAbstractions",
    "authority": "proof-bound dynamic custody",
    "fixed_hardware_boot_slot": false
  }
});
    if (typeof module !== 'undefined' && module.exports) module.exports = identity;
    root.BankLumpIdentity = identity;
})(typeof window !== 'undefined' ? window : globalThis);
