'use strict';
// Generated by scripts/build_bank_lump.js. Do not hand edit.
(function exposeBankLumpIdentity(root) {
    const identity = Object.freeze({
  "dot_name": "Bank",
  "issue_n": 1,
  "token": "f386f8fe",
  "binary_hash": "363a58a895fa5a6e8c596d881c637bfe26d6cce58314d64ee6d76a02a231a203",
  "identity_hash": "3b19718e37c1f36fcca3457e3016ec722737bd33103fac22f1c616de0fd63b11",
  "self_gt": 186216846,
  "ns_slot": null,
  "ns_slot_policy": "dynamic",
  "boot_resident": false,
  "runtime_binding": {
    "registry_index": 54,
    "dispatch": "SystemAbstractions",
    "authority": "proof-bound dynamic custody",
    "credential_abi": "capability-register-v1",
    "fixed_hardware_boot_slot": false
  },
  "capability_abi": {
    "Create": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "inputs": [
        {
          "name": "lump",
          "register": "CR1",
          "kind": "capability",
          "secure_type": "Inform",
          "rights": [
            "R"
          ]
        }
      ],
      "returns": {
        "name": "variable",
        "register": "CR3",
        "kind": "capability",
        "secure_type": "BankVariable",
        "rights": [
          "E"
        ]
      }
    },
    "Read": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "inputs": [
        {
          "name": "variable",
          "register": "CR3",
          "kind": "capability",
          "secure_type": "BankVariable",
          "rights": [
            "E"
          ]
        },
        {
          "name": "offset",
          "register": "DR1",
          "kind": "value"
        },
        {
          "name": "words",
          "register": "DR2",
          "kind": "value"
        }
      ],
      "returns": {
        "name": "readable",
        "register": "CR4",
        "kind": "capability",
        "secure_type": "Inform",
        "rights": [
          "R"
        ]
      }
    },
    "InspectVariable": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "inputs": [
        {
          "name": "variable",
          "register": "CR3",
          "kind": "capability",
          "secure_type": "BankVariable",
          "rights": [
            "E"
          ]
        }
      ],
      "returns": {
        "name": "word_count",
        "register": "DR1",
        "kind": "value"
      },
      "outputs": [
        {
          "name": "word_count",
          "register": "DR1",
          "kind": "value"
        },
        {
          "name": "capacity",
          "register": "DR2",
          "kind": "value"
        },
        {
          "name": "issue_n",
          "register": "DR3",
          "kind": "value"
        },
        {
          "name": "lifecycle",
          "register": "DR4",
          "kind": "value",
          "values": {
            "active": 1,
            "released": 2,
            "revoked": 3,
            "quarantined": 4
          }
        }
      ]
    },
    "Release": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "inputs": [
        {
          "name": "variable",
          "register": "CR3",
          "kind": "capability",
          "secure_type": "BankVariable",
          "rights": [
            "E"
          ]
        }
      ],
      "returns": {
        "name": "status",
        "register": "DR0",
        "kind": "value"
      }
    },
    "RevokeVariable": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "inputs": [
        {
          "name": "variable",
          "register": "CR3",
          "kind": "capability",
          "secure_type": "BankVariable",
          "rights": [
            "E"
          ]
        }
      ],
      "returns": {
        "name": "status",
        "register": "DR0",
        "kind": "value"
      }
    },
    "MintKey": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "returns": {
        "name": "owner_key",
        "register": "CR1",
        "kind": "capability",
        "secure_type": "BankOwnerKey"
      }
    },
    "Withdraw": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "returns": {
        "name": "valuable",
        "register": "CR2",
        "kind": "capability",
        "secure_type": "Inform"
      }
    },
    "ObtainPassKey": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "returns": {
        "name": "owner_key",
        "register": "CR1",
        "kind": "capability",
        "secure_type": "BankOwnerKey"
      }
    },
    "Recover": {
      "status": {
        "register": "DR0",
        "kind": "value"
      },
      "returns": {
        "name": "owner_key",
        "register": "CR1",
        "kind": "capability",
        "secure_type": "BankOwnerKey"
      }
    }
  }
});
    if (typeof module !== 'undefined' && module.exports) module.exports = identity;
    root.BankLumpIdentity = identity;
})(typeof window !== 'undefined' ? window : globalThis);
