'use strict';
const assert = require('node:assert/strict');
const { protectMemory } = require('./idx1-memory.js');
const original = Uint32Array.from([1, 2, 3, 4, 5, 6]);
const gate = protectMemory(original);
const memory = gate.memory;
gate.protect(2, 4);
original[2] = 99;
assert.equal(memory[2], 3);
assert.equal(protectMemory(memory), gate);
const denied = action => {
    const before = [...memory];
    assert.throws(action, error => error.code === 'IDX1_READ_ONLY');
    assert.deepEqual([...memory], before);
};
denied(() => { memory[2] = 9; });
denied(() => memory.set([9, 9, 9], 1));
denied(() => memory.fill(9));
denied(() => memory.copyWithin(0, 3));
denied(() => memory.reverse());
denied(() => memory.sort((a, b) => b - a));
denied(() => gate.requireWritable(1, 4));
memory[0] = 12;
memory.set([13], 1);
assert.deepEqual([...memory], [12, 13, 3, 4, 5, 6]);
new Uint32Array(memory.buffer)[2] = 99;
memory.subarray(2, 4)[0] = 99;
memory.forEach((value, index, exposed) => { exposed[2] = 99; });
assert.equal(memory[2], 3);
assert.throws(() => Object.defineProperty(memory, '2', { value: 99 }), TypeError);
assert.throws(() => { delete memory[2]; }, TypeError);
assert.throws(() => Object.setPrototypeOf(memory, {}), TypeError);
assert.equal(memory.byteLength, 24);
assert(memory instanceof Uint32Array);
assert.throws(() => gate.protect(2, 100), RangeError);
console.log('IDX1 installed-memory mutation gate tests passed');