'use strict';
// Generated from shared/thread_design.json by scripts/gen-thread-design.js.
// Do not edit this file directly; the JSON contract is the normative source.
(function (root, factory) {
    var raw = {
    "name": "Church Machine Thread",
    "normative": true,
    "header": {
        "typ": 2,
        "stackField": "cw",
        "stackAlias": "sw",
        "heapField": "cc"
    },
    "supportedBodyWords": [
        256
    ],
    "unsupportedBodyPolicy": "reject",
    "canonicalBodyWords": 256,
    "headerOffset": 0,
    "dataRegisters": {
        "first": 0,
        "last": 15,
        "offset": 1,
        "words": 16
    },
    "protectedStoOffset": 17,
    "protectedIndicator": {
        "stoBits": [
            0,
            11
        ],
        "sizeBit": 12,
        "reservedBits": [
            13,
            27
        ],
        "flagsBits": [
            28,
            31
        ]
    },
    "heapOffset": 18,
    "capabilityHomes": {
        "firstRegister": 0,
        "lastRegister": 11,
        "offset": 244,
        "words": 12
    },
    "runtimeCapabilityRegisters": [
        12,
        13,
        14,
        15
    ],
    "privateAbiWords": 256,
    "zoneOrder": [
        "Header",
        "Data Registers",
        "Protected STO",
        "Heap",
        "Freespace",
        "LIFO Stack",
        "Capabilities"
    ]
};
    var design = factory(raw);
    if (typeof module !== 'undefined' && module.exports) module.exports = design;
    if (root) root.ThreadDesign = design;
})(typeof globalThis !== 'undefined' ? globalThis : this, function (raw) {
    function layout(lumpSize, stackWords, heapWords) {
        lumpSize = Number(lumpSize);
        stackWords = Number(stackWords);
        heapWords = Number(heapWords);
        var capsStart = raw.capabilityHomes.offset;
        var capsEnd = capsStart + raw.capabilityHomes.words - 1;
        var heapStart = raw.heapOffset;
        var heapEnd = heapStart + heapWords - 1;
        var stackEnd = capsStart - 1;
        var stackStart = capsStart - stackWords;
        var freeStart = heapEnd + 1;
        var freeEnd = stackStart - 1;
        var supported = raw.supportedBodyWords.indexOf(lumpSize) !== -1;
        var valid = supported && stackWords > 0 && heapWords > 0 &&
            heapEnd < stackStart && capsEnd < raw.privateAbiWords;
        return Object.freeze({
            valid: valid,
            sizeSupported: supported,
            lumpSize: lumpSize,
            headerOffset: raw.headerOffset,
            drStart: raw.dataRegisters.offset,
            drEnd: raw.dataRegisters.offset + raw.dataRegisters.words - 1,
            drWords: raw.dataRegisters.words,
            protectedStoOffset: raw.protectedStoOffset,
            protectedIndicator: raw.protectedIndicator,
            heapStart: heapStart,
            heapEnd: heapEnd,
            heapWords: heapWords,
            freeStart: freeStart,
            freeEnd: freeEnd,
            freeWords: Math.max(0, freeEnd - freeStart + 1),
            stackStart: stackStart,
            stackEnd: stackEnd,
            stackWords: stackWords,
            capsStart: capsStart,
            capsEnd: capsEnd,
            capsWords: raw.capabilityHomes.words,
            privateZoneWords: raw.privateAbiWords
        });
    }
    return Object.freeze(Object.assign({}, raw, { layout: layout }));
});
