"""Focused server-image contracts for Task #3447 boot preparation.

These tests intentionally inspect generated bytes rather than driving the
simulator.  The browser/runtime execution path has separate coverage; the
contract here is that the server produces and preserves the exact persisted
Boot.Thread CR0 authority used by the three-instruction ROM.
"""

import json
import os
import struct
import sys
import base64
from unittest.mock import patch

import pytest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)

from server.boot_image import (  # noqa: E402
    NS_ENTRY_WORDS,
    create_gt,
    generate_boot_image,
    integrity32,
    read_boot_entry_info,
    thread_layout,
    validate_boot_image,
)

LUMPS_DIR = os.path.join(ROOT, "server", "lumps")


@pytest.fixture
def client():
    from server.app import app

    app.config["TESTING"] = True
    with app.test_client() as test_client:
        token = os.environ.get("REPORT_TOKEN", "").strip()
        if token:
            test_client.environ_base["HTTP_AUTHORIZATION"] = f"Bearer {token}"
        yield test_client


def _cfg(thread_count=1):
    return {
        "step1": {
            "totalNamespaceWords": 16384,
            "namespaceLumpWords": 64,
            "threadLumpWords": 256,
            "threadCount": thread_count,
        },
    }


def _words(image):
    return list(struct.unpack(f"<{len(image) // 4}I", image))


def _thread_home_index(words):
    total = len(words)
    thread_loc = words[total - 2 * NS_ENTRY_WORDS]
    header = words[thread_loc]
    size = 1 << (((header >> 23) & 0xF) + 6)
    layout = thread_layout(size, (header >> 10) & 0x1FFF)
    assert layout["valid"]
    return thread_loc + layout["caps_start"]


def test_selected_target_sequence_is_serialized_in_layout_derived_cr0_home():
    image = generate_boot_image(_cfg(), LUMPS_DIR, boot_entry_slot=10)
    info = read_boot_entry_info(image)

    assert info["entry_slot"] == 10
    assert info["thread_caps_offset"] == 244
    assert info["thread_caps0"] == create_gt(
        info["entry_gt_seq"], 10, {"E": 1}, 1)
    assert info["caps0_ok"] is True


def test_reissued_selected_target_requires_matching_current_sequence_in_home():
    image = generate_boot_image(_cfg(), LUMPS_DIR, boot_entry_slot=10)
    words = _words(image)
    total = len(words)
    target_base = total - (10 + 1) * NS_ENTRY_WORDS
    sequence = 7
    words[target_base + 1] = (
        (words[target_base + 1] & ~(0x1FF << 21)) | (sequence << 21))
    words[target_base + 2] = integrity32(
        words[target_base], words[target_base + 1])
    current_gt = create_gt(sequence, 10, {"E": 1}, 1)
    thread_loc = words[total - 2 * NS_ENTRY_WORDS]
    header = words[thread_loc]
    layout = thread_layout(
        1 << (((header >> 23) & 0xF) + 6), (header >> 10) & 0x1FFF)
    words[thread_loc + layout["caps_start"]] = current_gt
    # The selected Boot.Thread continuation is part of the same prepared
    # primary context and must carry the destination descriptor's generation.
    words[thread_loc + layout["stack_end"] - 1] = current_gt
    reissued = struct.pack(f"<{total}I", *words)

    validate_boot_image(reissued)
    info = read_boot_entry_info(reissued)
    assert info["entry_gt_seq"] == sequence
    assert info["thread_caps0"] == create_gt(sequence, 10, {"E": 1}, 1)


@pytest.mark.parametrize("replacement, match", [
    (0, "CR0 home is missing"),
    (create_gt(0, 6, {"E": 1}, 1), "CR0 home is stale"),
])
def test_missing_or_stale_imported_cr0_home_is_detected_without_repair(
        replacement, match):
    image = generate_boot_image(_cfg(), LUMPS_DIR, boot_entry_slot=10)
    words = _words(image)
    words[_thread_home_index(words)] = replacement
    corrupted = struct.pack(f"<{len(words)}I", *words)

    with pytest.raises(ValueError, match=match):
        validate_boot_image(corrupted)


def test_selecting_boot_target_does_not_retarget_secondary_thread_context():
    cfg = _cfg(thread_count=2)
    default = _words(generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=6))
    selected = _words(generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=10))
    total = len(default)
    secondary_loc = default[total - (11 + 1) * NS_ENTRY_WORDS]
    secondary_size = 256

    assert selected[secondary_loc:secondary_loc + secondary_size] == (
        default[secondary_loc:secondary_loc + secondary_size])


def test_generate_endpoint_rejects_unsaved_entry_override(client, tmp_path, monkeypatch):
    """Generation cannot use an entrySlot that disagrees with saved selection."""
    import server.app as app_module

    cfg = _cfg()
    cfg.update({"targetBoard": "wukong-xc7a100t", "bootEntrySlot": 10})
    config_path = tmp_path / "boot-config.json"
    with open(config_path, "w", encoding="utf-8") as source:
        json.dump(cfg, source)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))

    response = client.post("/api/boot-image/generate", json={"entrySlot": 6})
    assert response.status_code == 409
    assert "does not silently change" in response.get_json()["error"]


def test_generate_endpoint_requires_explicit_saved_entry_selection(
        client, tmp_path, monkeypatch):
    import server.app as app_module

    config_path = tmp_path / "boot-config.json"
    config_path.write_text(json.dumps({
        **_cfg(),
        "targetBoard": "wukong-xc7a100t",
    }), encoding="utf-8")
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))

    response = client.post("/api/boot-image/generate", json={})

    assert response.status_code == 409
    assert "no Lightning Bolt bootEntrySlot" in response.get_json()["error"]


def test_boot_config_mutation_requires_report_token_when_configured(monkeypatch):
    import server.app as app_module

    monkeypatch.setenv("REPORT_TOKEN", "scoped-boot-config-token")
    app_module.app.config["TESTING"] = True
    with app_module.app.test_client() as unauthenticated:
        response = unauthenticated.post("/api/boot-config", json={})

    assert response.status_code == 401
    assert "REPORT_TOKEN" in response.get_json()["error"]


def test_failed_selection_preflight_leaves_saved_config_and_image_unchanged(
        client, tmp_path, monkeypatch):
    """A target that cannot be prepared never becomes a visible selection."""
    import server.app as app_module

    config_path = tmp_path / "boot-config.json"
    image_path = tmp_path / "boot-image.bin"
    original_cfg = {
        **_cfg(),
        "targetBoard": "wukong-xc7a100t",
        "bootEntrySlot": 10,
    }
    original_text = json.dumps(original_cfg, indent=2)
    original_image = b"previous-committed-image"
    config_path.write_text(original_text, encoding="utf-8")
    image_path.write_bytes(original_image)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(image_path))
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH",
        str(tmp_path / "boot-image.provenance.json"))

    response = client.post("/api/boot-config", json={
        **original_cfg,
        "bootEntrySlot": 2,  # UART MMIO is not executable and cannot prepare.
        "prepareBootEntry": True,
    })

    assert response.status_code == 422
    assert response.get_json()["prepared"] is False
    assert config_path.read_text(encoding="utf-8") == original_text
    assert image_path.read_bytes() == original_image


def test_selection_patch_preserves_existing_secondary_thread_bytes(
        tmp_path, monkeypatch):
    """Preparing Thread.1 must not rebuild/mutate persisted Thread.2 state."""
    import server.app as app_module

    cfg = {**_cfg(thread_count=2), "bootEntrySlot": 6}
    existing = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=6)
    provenance_path = tmp_path / "boot-image.provenance.json"
    provenance = app_module._boot_image_gen.build_boot_image_provenance(
        existing, LUMPS_DIR)
    provenance["origin"] = "generated"
    provenance_path.write_text(json.dumps(provenance), encoding="utf-8")
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))
    words = _words(existing)
    total = len(words)
    secondary_loc = words[total - (11 + 1) * NS_ENTRY_WORDS]
    secondary_before = words[secondary_loc:secondary_loc + 256]

    prepared = app_module._prepare_selected_boot_image(
        existing, {**cfg, "bootEntrySlot": 10}, 10)
    prepared_words = _words(prepared)

    # Selection authority has exactly three writable homes: Header BootEntry,
    # Boot.Thread CR0, and the explicit SelfTest Next.GT c-list row.  In
    # particular, no suspended Thread frame / Enter identity is retargeted.
    thread_loc = words[total - 2 * NS_ENTRY_WORDS]
    thread_header = words[thread_loc]
    thread_size = 1 << (((thread_header >> 23) & 0xF) + 6)
    thread_layout_info = thread_layout(
        thread_size, (thread_header >> 10) & 0x1FFF)
    selftest_loc = words[total - 7 * NS_ENTRY_WORDS]
    selftest_header = words[selftest_loc]
    selftest_size = 1 << (((selftest_header >> 23) & 0xF) + 6)
    selftest_next = selftest_loc + selftest_size - (selftest_header & 0xFF) + 1
    changed = {index for index, (before, after) in enumerate(
        zip(words, prepared_words)) if before != after}
    assert changed == {
        4,
        thread_loc + thread_layout_info["caps_start"],
        selftest_next,
    }
    assert prepared_words[secondary_loc:secondary_loc + 256] == secondary_before
    assert read_boot_entry_info(prepared)["entry_slot"] == 10


def test_selection_patch_rejects_target_identity_that_differs_from_provenance(
        tmp_path, monkeypatch):
    """Slot/sequence equality cannot authorize a different LUMP body/policy."""
    import server.app as app_module

    cfg = {**_cfg(), "bootEntrySlot": 6}
    existing = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=6)
    provenance = app_module._boot_image_gen.build_boot_image_provenance(
        existing, LUMPS_DIR)
    provenance["origin"] = "generated"
    target_row = next(row for row in provenance["resident_bindings"]
                      if row["slot"] == 10)
    target_row["token"] = "different-token"
    provenance_path = tmp_path / "boot-image.provenance.json"
    provenance_path.write_text(json.dumps(provenance), encoding="utf-8")
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))

    with pytest.raises(ValueError, match="filename, token, or load policy"):
        app_module._prepare_selected_boot_image(
            existing, {**cfg, "bootEntrySlot": 10}, 10)


def test_selecting_selftest_couples_explicit_next_gt_to_selected_target(
        tmp_path, monkeypatch):
    """SelfTest Next.GT follows every selected Lightning Bolt target."""
    import server.app as app_module

    cfg = {**_cfg(), "bootEntrySlot": 10}
    existing = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=10)
    provenance = app_module._boot_image_gen.build_boot_image_provenance(
        existing, LUMPS_DIR)
    provenance["origin"] = "generated"
    provenance_path = tmp_path / "boot-image.provenance.json"
    provenance_path.write_text(json.dumps(provenance), encoding="utf-8")
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))
    words = _words(existing)
    total = len(words)
    selftest_loc = words[total - 7 * NS_ENTRY_WORDS]
    selftest_header = words[selftest_loc]
    selftest_size = 1 << (((selftest_header >> 23) & 0xF) + 6)
    next_index = selftest_loc + selftest_size - (selftest_header & 0xFF) + 1

    prepared = _words(app_module._prepare_selected_boot_image(
        existing, {**cfg, "bootEntrySlot": 6}, 6))

    assert prepared[next_index] == create_gt(0, 6, {"E": 1}, 1)
    assert prepared[next_index] != words[next_index]
    assert read_boot_entry_info(struct.pack(f"<{total}I", *prepared))["entry_slot"] == 6


def test_image_commit_failure_rolls_back_saved_selection_and_all_files(
        client, tmp_path, monkeypatch):
    """An injected write failure cannot leave config ahead of the image."""
    import server.app as app_module

    config_path = tmp_path / "boot-config.json"
    image_path = tmp_path / "boot-image.bin"
    provenance_path = tmp_path / "boot-image.provenance.json"
    original_cfg = {
        **_cfg(),
        "targetBoard": "wukong-xc7a100t",
        "bootEntrySlot": 6,
    }
    original_text = json.dumps(original_cfg, indent=2)
    original_image = generate_boot_image(original_cfg, LUMPS_DIR, boot_entry_slot=6)
    original_provenance_data = app_module._boot_image_gen.build_boot_image_provenance(
        original_image, LUMPS_DIR)
    original_provenance_data["origin"] = "generated"
    original_provenance = json.dumps(original_provenance_data).encode("utf-8")
    config_path.write_text(original_text, encoding="utf-8")
    image_path.write_bytes(original_image)
    provenance_path.write_bytes(original_provenance)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(image_path))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))

    with patch.object(app_module, "_write_boot_image_bytes",
                      side_effect=OSError("injected image write failure")):
        response = client.post("/api/boot-config", json={
            **original_cfg,
            "bootEntrySlot": 10,
            "prepareBootEntry": True,
        })

    assert response.status_code == 500
    assert config_path.read_text(encoding="utf-8") == original_text
    assert image_path.read_bytes() == original_image
    assert provenance_path.read_bytes() == original_provenance


def test_image_writer_rolls_back_image_provenance_and_ns_state_on_failure(
        tmp_path, monkeypatch):
    """A failure after replacement cannot publish an image/provenance hybrid."""
    import server.app as app_module

    image_path = tmp_path / "boot-image.bin"
    provenance_path = tmp_path / "boot-image.provenance.json"
    state_path = tmp_path / "ns-state.json"
    old_image = b"old image"
    old_provenance = b'{"origin":"imported","image_sha256":"old"}'
    old_state = b'{"abstractions":[],"committed_raw_fingerprint":"old"}'
    image_path.write_bytes(old_image)
    provenance_path.write_bytes(old_provenance)
    state_path.write_bytes(old_state)
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(image_path))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(state_path))
    candidate = generate_boot_image(_cfg(), LUMPS_DIR, boot_entry_slot=6)

    with patch.object(app_module, "_invalidate_ns_state_raw_binding",
                      side_effect=OSError("injected state invalidation failure")):
        with pytest.raises(OSError, match="injected state invalidation failure"):
            app_module._write_boot_image_bytes(candidate, provenance_origin="imported")

    assert image_path.read_bytes() == old_image
    assert provenance_path.read_bytes() == old_provenance
    assert state_path.read_bytes() == old_state


def test_save_ns_failure_restores_exact_prior_provenance_and_state(
        client, tmp_path, monkeypatch):
    """Save NS must not recreate rollback provenance through the image writer."""
    import server.app as app_module

    cfg = {**_cfg(), "targetBoard": "wukong-xc7a100t", "bootEntrySlot": 6}
    candidate = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=6)
    config_path = tmp_path / "boot-config.json"
    image_path = tmp_path / "boot-image.bin"
    provenance_path = tmp_path / "boot-image.provenance.json"
    state_path = tmp_path / "ns-state.json"
    old_config = json.dumps(cfg).encode("utf-8")
    old_image = b"old-image"
    old_provenance = b'{"origin":"imported","image_sha256":"old"}'
    old_state = b'{"abstractions":[],"committed_raw_fingerprint":"old"}'
    config_path.write_bytes(old_config)
    image_path.write_bytes(old_image)
    provenance_path.write_bytes(old_provenance)
    state_path.write_bytes(old_state)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(image_path))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(state_path))

    with patch.object(app_module, "_write_ns_state",
                      side_effect=OSError("injected ns-state write failure")):
        response = client.post("/api/boot-image/save-ns", json={
            "data_b64": base64.b64encode(candidate).decode("ascii"),
            "ns_state": {"abstractions": []},
        })

    assert response.status_code == 500
    assert config_path.read_bytes() == old_config
    assert image_path.read_bytes() == old_image
    assert provenance_path.read_bytes() == old_provenance
    assert state_path.read_bytes() == old_state


def test_save_ns_commits_boot_config_candidate_with_matching_image(
        client, tmp_path, monkeypatch):
    """A drag selection commits config and image together through Save NS."""
    import server.app as app_module

    cfg = {**_cfg(), "targetBoard": "wukong-xc7a100t", "bootEntrySlot": 10}
    image = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=10)
    config_path = tmp_path / "boot-config.json"
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(tmp_path / "boot-image.bin"))
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH",
        str(tmp_path / "boot-image.provenance.json"))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(tmp_path / "ns-state.json"))

    response = client.post("/api/boot-image/save-ns", json={
        "data_b64": base64.b64encode(image).decode("ascii"),
        "ns_state": {"abstractions": []},
        "boot_config": cfg,
    })

    body = response.get_json()
    assert response.status_code == 200, body
    assert body["config"]["bootEntrySlot"] == 10
    assert body["preparation"]["status"] == "prepared"
    assert body["bytes"] == len(image)
    assert body["words"] == len(image) // 4
    assert body["binaryUrl"] == "/api/boot-image/binary"
    assert json.loads(config_path.read_text())["bootEntrySlot"] == 10
    provenance = json.loads(
        (tmp_path / "boot-image.provenance.json").read_text(encoding="utf-8"))
    assert provenance["boot_config_sha256"] == app_module._boot_config_freshness_digest(
        body["config"])
    assert provenance["source_sha256"]["ns_state"] == app_module._file_sha256(
        str(tmp_path / "ns-state.json"))
    assert provenance["source_sha256"]["manifest"] == app_module._file_sha256(
        os.path.join(LUMPS_DIR, "manifest.json"))
    # Exercise the real stale check rather than a writer stub: final image
    # provenance/timestamp must describe the state committed by this save.
    binary = client.get("/api/boot-image/binary")
    exists = client.get("/api/boot-image/exists")
    assert binary.status_code == 200, binary.get_json()
    assert binary.data == image
    assert exists.get_json()["exists"] is True
    assert read_boot_entry_info(binary.data)["entry_slot"] == 10
    # The download route must not bypass the same source-hash freshness gate.
    state_path = tmp_path / "ns-state.json"
    source_state = json.loads(state_path.read_text(encoding="utf-8"))
    source_state["freshness_probe"] = "changed"
    state_path.write_text(json.dumps(source_state), encoding="utf-8")
    stale_download = client.get("/api/boot-image/download")
    assert stale_download.status_code == 409
    assert stale_download.get_json()["needsPrepare"] is True


def test_save_ns_couples_browser_prepared_selftest_next_gt_before_commit(
        client, tmp_path, monkeypatch):
    """Save NS serializes the server-equivalent Next.GT, not demo-only state."""
    import server.app as app_module

    initial_cfg = {**_cfg(), "targetBoard": "wukong-xc7a100t", "bootEntrySlot": 6}
    candidate_cfg = {**initial_cfg, "bootEntrySlot": 10}
    words = _words(generate_boot_image(initial_cfg, LUMPS_DIR, boot_entry_slot=6))
    total = len(words)
    target_base = total - (10 + 1) * NS_ENTRY_WORDS
    target_loc, target_authority = words[target_base], words[target_base + 1]
    target_gt = create_gt((target_authority >> 21) & 0x1FF, 10, {"E": 1}, 1)
    # These are exactly the two homes the browser core prepares. Deliberately
    # leave the serialized SelfTest continuation at its old NS[6] value.
    words[4] = target_loc * 4
    words[_thread_home_index(words)] = target_gt
    browser_candidate = struct.pack(f"<{total}I", *words)
    selftest_loc = words[total - (6 + 1) * NS_ENTRY_WORDS]
    selftest_header = words[selftest_loc]
    selftest_next = selftest_loc + (1 << (((selftest_header >> 23) & 0xF) + 6)
        ) - (selftest_header & 0xFF) + 1
    assert words[selftest_next] != target_gt

    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(tmp_path / "boot-config.json"))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(tmp_path / "boot-image.bin"))
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH",
        str(tmp_path / "boot-image.provenance.json"))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(tmp_path / "ns-state.json"))
    saved = client.post("/api/boot-image/save-ns", json={
        "data_b64": base64.b64encode(browser_candidate).decode("ascii"),
        "ns_state": {"abstractions": []},
        "boot_config": candidate_cfg,
    })
    assert saved.status_code == 200, saved.get_json()
    final_image = client.get("/api/boot-image/binary")
    assert final_image.status_code == 200, final_image.get_json()
    final_words = _words(final_image.data)
    changed = {i for i, (old, new) in enumerate(zip(words, final_words))
               if old != new}
    assert changed == {selftest_next}
    assert final_words[selftest_next] == target_gt
    assert read_boot_entry_info(final_image.data)["entry_slot"] == 10


@pytest.mark.parametrize("edit", ("geometry", "policy"))
def test_normal_designer_save_stales_existing_image_until_explicit_prepare(
        client, tmp_path, monkeypatch, edit):
    """Repeating bootEntrySlot is not an implicit image Prepare permission."""
    import server.app as app_module

    cfg = {
        **_cfg(), "targetBoard": "wukong-xc7a100t", "bootEntrySlot": 10,
        "step2": {"lumps": []}, "step3": {"emptySlotCount": 0},
    }
    image = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=10)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(tmp_path / "boot-config.json"))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(tmp_path / "boot-image.bin"))
    monkeypatch.setattr(
        app_module, "BOOT_IMAGE_PROVENANCE_PATH",
        str(tmp_path / "boot-image.provenance.json"))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(tmp_path / "ns-state.json"))
    saved = client.post("/api/boot-image/save-ns", json={
        "data_b64": base64.b64encode(image).decode("ascii"),
        "ns_state": {"abstractions": []},
        "boot_config": cfg,
    })
    assert saved.status_code == 200, saved.get_json()

    updated = json.loads(json.dumps(cfg))
    if edit == "geometry":
        updated["step1"]["totalNamespaceWords"] = 8192
    else:
        updated["slotRules"] = {"10": "LightningBolt"}
    # This deliberately includes the unchanged selected slot, as every normal
    # Designer save does.  It must write config without republishing bytes.
    response = client.post("/api/boot-config", json=updated)
    assert response.status_code == 200, response.get_json()
    assert response.get_json()["prepared"] is False
    assert response.get_json()["bootImageInvalidated"] is True
    assert client.get("/api/boot-image/binary").status_code == 409
    assert client.get("/api/boot-image/download").status_code == 409
    exists = client.get("/api/boot-image/exists").get_json()
    assert exists["exists"] is False
    assert exists["needsPrepare"] is True


def test_save_ns_candidate_validation_and_config_write_failure_leave_all_files(
        client, tmp_path, monkeypatch):
    """Invalid candidates and final config-write failures publish no hybrid."""
    import server.app as app_module

    cfg = {**_cfg(), "targetBoard": "wukong-xc7a100t", "bootEntrySlot": 6}
    image = generate_boot_image(cfg, LUMPS_DIR, boot_entry_slot=6)
    config_path = tmp_path / "boot-config.json"
    image_path = tmp_path / "boot-image.bin"
    provenance_path = tmp_path / "boot-image.provenance.json"
    state_path = tmp_path / "ns-state.json"
    original = {
        config_path: b'{"old":"config"}',
        image_path: b"old-image",
        provenance_path: b'{"old":"provenance"}',
        state_path: b'{"abstractions":[],"committed_raw_fingerprint":"old"}',
    }
    for path, content in original.items():
        path.write_bytes(content)
    monkeypatch.setattr(app_module, "BOOT_CONFIG_PATH", str(config_path))
    monkeypatch.setattr(
        app_module, "BOOT_CONFIG_LEGACY_PATH", str(tmp_path / "no-legacy.json"))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PATH", str(image_path))
    monkeypatch.setattr(app_module, "BOOT_IMAGE_PROVENANCE_PATH", str(provenance_path))
    monkeypatch.setattr(app_module, "NS_STATE_PATH", str(state_path))
    payload = {
        "data_b64": base64.b64encode(image).decode("ascii"),
        "ns_state": {"abstractions": []},
        "boot_config": cfg,
    }

    invalid = dict(payload, boot_config={**cfg, "targetBoard": "not-a-board"})
    invalid_response = client.post("/api/boot-image/save-ns", json=invalid)
    assert invalid_response.status_code == 400
    assert all(path.read_bytes() == content for path, content in original.items())

    with patch.object(app_module, "_atomic_write_json",
                      side_effect=OSError("injected config write failure")):
        failed_response = client.post("/api/boot-image/save-ns", json=payload)
    assert failed_response.status_code == 500
    assert all(path.read_bytes() == content for path, content in original.items())