## Vivado batch build script — QMTECH Wukong XC7A100T Church Machine LED Flash
## ============================================================================
## Usage (from the directory containing the extracted ZIP):
##
##   vivado -mode batch -source wukong_xc7a100t.tcl
##
##   To override the timing gate (emergency / research builds only):
##   vivado -mode batch -source wukong_xc7a100t.tcl -tclargs --allow-timing-violations
##
## Prerequisites:
##   • Vivado 2020.x or later (WebPACK edition — free, covers Artix-7)
##   • church_wukong_xc7a100t.v   — Verilog netlist (generated by gen_rtlil.py)
##   • wukong_xc7a100t.xdc        — Pin / timing constraints (this directory)
##
## Output:
##   church_wukong_xc7a100t.bit   — Bitstream, copied here after write_bitstream
##
## Programming (after synthesis completes):
##   Option A — Vivado Hardware Manager (GUI):
##     open_hw_manager → connect_hw_server → open_hw_target
##     → Program Device → select church_wukong_xc7a100t.bit
##   Option B — Vivado Hardware Manager (batch):
##     See the Tcl snippet printed at the end of this script.
##   Option C — xc3sprog (Chromebook Linux with Platform Cable USB II):
##     xc3sprog -c xpc -p 0 church_wukong_xc7a100t.bit
## ============================================================================

set PART     "xc7a100tfgg676-2"
set TOP      "church_wukong_xc7a100t"
set PROJ_DIR "./vivado_wukong"
set JOBS     4

## ── Create Vivado project ──────────────────────────────────────────────────
create_project -force ${TOP} ${PROJ_DIR} -part ${PART}
set_property target_language Verilog [current_project]

## ── Add Verilog netlist ────────────────────────────────────────────────────
if {![file exists ${TOP}.v]} {
    error "Source not found: ${TOP}.v\nRun 'python -m hardware.gen_rtlil --wukong' first."
}
add_files -norecurse [list ${TOP}.v]
set_property file_type {Verilog} [get_files ${TOP}.v]

## ── Add constraints ────────────────────────────────────────────────────────
if {![file exists wukong_xc7a100t.xdc]} {
    error "Constraints not found: wukong_xc7a100t.xdc"
}
add_files -fileset constrs_1 -norecurse wukong_xc7a100t.xdc
set_property is_enabled true [get_files wukong_xc7a100t.xdc]

## ── Set top-level module ──────────────────────────────────────────────────
set_property top ${TOP} [current_fileset]
update_compile_order -fileset sources_1

## ── Synthesis ────────────────────────────────────────────────────────────
puts "\n═══ Synthesis starting (may take 5–15 min) ═══"
launch_runs synth_1 -jobs ${JOBS}
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/synth_1/*.log]
    error "Synthesis FAILED — check: $log"
}
puts "Synthesis complete."

## ── Implementation ───────────────────────────────────────────────────────
puts "\n═══ Implementation starting (may take 10–25 min) ═══"
launch_runs impl_1 -jobs ${JOBS}
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/impl_1/*.log]
    error "Implementation FAILED — check: $log"
}
puts "Implementation complete."

## ── Timing gate ──────────────────────────────────────────────────────────────
## A negative WNS means setup timing is violated — the bitstream will produce
## intermittent or completely wrong behaviour on the real board.  The build
## therefore fails here rather than silently producing a broken bitstream.
##
## Override (emergency / research only):
##   vivado -mode batch -source wukong_xc7a100t.tcl -tclargs --allow-timing-violations
set allow_timing_violations 0
if {[lsearch -exact $argv "--allow-timing-violations"] >= 0} {
    set allow_timing_violations 1
}

set wns [get_property STATS.WNS [get_runs impl_1]]
if {$wns ne "" && $wns < 0} {
    if {$allow_timing_violations} {
        puts "WARNING: Timing violation — WNS = ${wns} ns."
        puts "WARNING: --allow-timing-violations was set; continuing with a broken bitstream."
        puts "WARNING: DO NOT use this bitstream on production hardware."
    } else {
        error "TIMING FAILURE: WNS = ${wns} ns (negative means setup violations exist).\nThis bitstream would behave incorrectly on real hardware and has NOT been written.\nFix the timing or pass --allow-timing-violations to override (not recommended)."
    }
} else {
    puts "Timing clean (WNS = ${wns} ns)."
}

## ── Bitstream generation ─────────────────────────────────────────────────
puts "\n═══ Generating bitstream ═══"
launch_runs impl_1 -to_step write_bitstream -jobs ${JOBS}
wait_on_run impl_1

## Copy bitstream to working directory for easy access
set bit_src "${PROJ_DIR}/${TOP}.runs/impl_1/${TOP}.bit"
if {[file exists $bit_src]} {
    file copy -force $bit_src ${TOP}.bit
    puts "\n═══════════════════════════════════════════════════════════════════"
    puts " Bitstream ready: [pwd]/${TOP}.bit"
    puts "═══════════════════════════════════════════════════════════════════"
    puts ""
    puts " To program via Vivado Hardware Manager (Tcl console):"
    puts "   open_hw_manager"
    puts "   connect_hw_server -allow_non_jtag"
    puts "   open_hw_target"
    puts "   set_property PROGRAM.FILE {[pwd]/${TOP}.bit} \[lindex \[get_hw_devices\] 0\]"
    puts "   program_hw_devices \[lindex \[get_hw_devices\] 0\]"
    puts ""
    puts " Expected LED behaviour after programming:"
    puts "   D1 (G21):  solid ON during boot (~50 cycles), then blinks ~1 Hz (CM MMIO-controlled)"
    puts "   D2 (G20):  1 Hz heartbeat during boot, then OFF when running (lit = fault latched)"
    puts "   UART E3:   0xBB sentinel byte at 57600 baud within ~1 s of power-on"
    puts "═══════════════════════════════════════════════════════════════════"
} else {
    error "Bitstream not found at $bit_src — check implementation logs."
}

## ── SPI flash image (MCS) ────────────────────────────────────────────────────
## Produces church_wukong_xc7a100t.mcs for programming the on-board SPI NOR flash.
##
## Flash device (QMTECH Wukong V3): Winbond W25Q256JVSIQ
##   Capacity : 256 Mb (32 MB)
##   Interface: SPI x1 / x2 / x4 (Quad SPI)
##   Voltage  : 2.7–3.6 V
##   Vivado part string: w25q256jvsiq-spi-x1_x2_x4
##     (verify with: get_cfgmem_parts *w25q256* — or use *256* to list all 256 Mb parts)
##
## After programming the flash and pressing the reset button the Church Machine
## boots automatically without re-programming the SRAM.
set mcs_file "[pwd]/${TOP}.mcs"
puts "\n═══ Generating SPI flash image (MCS) ═══"
write_cfgmem \
    -format       mcs       \
    -size         256       \
    -interface    SPIx4     \
    -loadbit      "up 0x0 [pwd]/${TOP}.bit" \
    -file         ${mcs_file} \
    -force
puts "\n═══════════════════════════════════════════════════════════════════"
puts " SPI flash image ready: ${mcs_file}"
puts "═══════════════════════════════════════════════════════════════════"
puts ""
puts " To program the SPI flash via Vivado Hardware Manager (Tcl console):"
puts "   # -- open connection (same as SRAM programming) --"
puts "   open_hw_manager"
puts "   connect_hw_server -allow_non_jtag"
puts "   open_hw_target"
puts "   set device \[lindex \[get_hw_devices\] 0\]"
puts "   refresh_hw_device -update_hw_probes false \$device"
puts ""
puts "   # -- attach flash and program it --"
puts "   create_hw_cfgmem -hw_device \$device \\"
puts "       \[lindex \[get_cfgmem_parts {w25q256jvsiq-spi-x1_x2_x4}\] 0\]"
puts "   set cfgmem \[get_property PROGRAM.HW_CFGMEM \$device\]"
puts "   set_property PROGRAM.BLANK_CHECK  0          \$cfgmem"
puts "   set_property PROGRAM.ERASE        1          \$cfgmem"
puts "   set_property PROGRAM.CFG_PROGRAM  1          \$cfgmem"
puts "   set_property PROGRAM.VERIFY       1          \$cfgmem"
puts "   set_property PROGRAM.FILES        \[list {${mcs_file}}\] \$cfgmem"
puts "   program_hw_cfgmem \$cfgmem"
puts "   boot_hw_device \$device"
puts ""
puts " After programming completes, press the RESET button on the Wukong board."
puts " The Church Machine will boot automatically (no re-programming needed)."
puts "═══════════════════════════════════════════════════════════════════"
