## Vivado batch build script — QMTECH Wukong XC7A100T Church Machine LED Flash
## ============================================================================
## Usage (from the directory containing the extracted ZIP):
##
##   vivado -mode batch -source wukong_xc7a100t.tcl
##
##   To override the timing gate (emergency / research builds only):
##   vivado -mode batch -source wukong_xc7a100t.tcl -tclargs --allow-timing-violations
##
## Prerequisites:
##   • Vivado 2020.x or later (WebPACK edition — free, covers Artix-7)
##   • church_wukong_xc7a100t.v   — Verilog netlist (generated by gen_rtlil.py)
##   • wukong_xc7a100t.xdc        — Pin / timing constraints (this directory)
##
## Output:
##   church_wukong_xc7a100t.bit   — Bitstream, copied here after write_bitstream
##
## Programming (after synthesis completes):
##   Option A — Vivado Hardware Manager (GUI):
##     open_hw_manager → connect_hw_server → open_hw_target
##     → Program Device → select church_wukong_xc7a100t.bit
##   Option B — Vivado Hardware Manager (batch):
##     See the Tcl snippet printed at the end of this script.
##   Option C — xc3sprog (Chromebook Linux with Platform Cable USB II):
##     xc3sprog -c xpc -p 0 church_wukong_xc7a100t.bit
## ============================================================================

set PART     "xc7a100tfgg676-2"
set TOP      "church_wukong_xc7a100t"
set PROJ_DIR "./vivado_wukong"
set JOBS     4

## ── ILA flag ─────────────────────────────────────────────────────────────────
## Set INSERT_ILA to 1 to insert a Xilinx ILA debug core so Vivado Hardware
## Manager can probe Church Machine internals live over JTAG.
##
## REQUIREMENT: Vivado Standard or Enterprise license (NOT WebPACK/BASIC).
##   With BASIC license leave this 0 — the build will still produce a correct
##   bitstream and SPI flash image; Hardware Manager just won't show CM probes.
##
## To override from the command line without editing this file:
##   vivado -mode batch -source wukong_xc7a100t.tcl -tclargs --insert-ila
set INSERT_ILA 0
if {[lsearch -exact $argv "--insert-ila"] >= 0} { set INSERT_ILA 1 }

## ── Create Vivado project ──────────────────────────────────────────────────
create_project -force ${TOP} ${PROJ_DIR} -part ${PART}
set_property target_language Verilog [current_project]

## ── Add Verilog netlist ────────────────────────────────────────────────────
if {![file exists ${TOP}.v]} {
    error "Source not found: ${TOP}.v\nRun 'python -m hardware.gen_rtlil --wukong' first."
}
add_files -norecurse [list ${TOP}.v]
set_property file_type {Verilog} [get_files ${TOP}.v]

## ── Add constraints ────────────────────────────────────────────────────────
if {![file exists wukong_xc7a100t.xdc]} {
    error "Constraints not found: wukong_xc7a100t.xdc"
}
add_files -fileset constrs_1 -norecurse wukong_xc7a100t.xdc
set_property is_enabled true [get_files wukong_xc7a100t.xdc]

## ── Set top-level module ──────────────────────────────────────────────────
set_property top ${TOP} [current_fileset]
update_compile_order -fileset sources_1

## ── Synthesis ────────────────────────────────────────────────────────────
puts "\n═══ Synthesis starting (may take 5–15 min) ═══"
launch_runs synth_1 -jobs ${JOBS}
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/synth_1/*.log]
    error "Synthesis FAILED — check: $log"
}
puts "Synthesis complete."

## ── ILA debug probe insertion (post-synthesis, Standard/Enterprise only) ──
## A Xilinx ILA (Integrated Logic Analyzer) core is inserted into the
## synthesised netlist so Vivado Hardware Manager can capture Church Machine
## state live over the board's built-in JTAG chain — no extra pins needed.
##
## Probe list (1024-sample capture depth):
##   probe0 [0]    dbg_boot_complete  — CM boot phase done; transitions 0→1 at boot
##   probe1 [0]    dbg_fault_valid    — live CM fault signal (any fault type)
##   probe2 [31:0] dbg_nia            — NIA of the most-recently retired instruction
##   probe3 [31:0] dbg_fault          — packed fault telemetry:
##                                        bits[4:0]   = 0 (reserved)
##                                        bit[5]      = retire_fault_valid
##                                        bits[10:6]  = retire_fault_code (fault type)
##                                        bits[31:11] = fault_gt[20:0] (GT word0 of faulting cap)
##   probe4 [1:0]  led                — physical LED state: [0]=led0 (D1), [1]=led1 (D2)
##                                      (ACTIVE-LOW: 0 = LED ON, 1 = LED OFF)
##
## REQUIRES: Vivado Standard or Enterprise license. Not available with BASIC/WebPACK.
## Enable by passing --insert-ila on the command line or setting INSERT_ILA 1 above.

if {$INSERT_ILA} {
    open_run synth_1 -name synth_1

    set ila [create_debug_core u_ila_0 ila]
    set_property C_DATA_DEPTH        1024  $ila
    set_property C_TRIGIN_EN         false $ila
    set_property C_EN_STRG_QUAL      false $ila
    set_property C_ADV_TRIGGER       false $ila
    set_property C_ALL_PROBE_SAME_MU_CNT 4 $ila

    ## Clock: connect to the BUFG output that drives the sync domain
    set clk_net [get_nets -hierarchical -filter {NAME =~ *clk_IBUF_BUFG* && IS_CLOCK == 1}]
    if {$clk_net eq ""} {
        set clk_net [lindex [get_nets -hierarchical -filter {IS_CLOCK == 1}] 0]
        puts "ILA: clk_IBUF_BUFG not found by name; using fallback clock net: $clk_net"
    }
    connect_debug_port u_ila_0/clk $clk_net

    ## probe0 — dbg_boot_complete (1-bit)
    create_debug_port u_ila_0 probe
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
    set_property port_width 1               [get_debug_ports u_ila_0/probe0]
    connect_debug_port u_ila_0/probe0 [get_nets {dbg_boot_complete}]

    ## probe1 — dbg_fault_valid (1-bit)
    create_debug_port u_ila_0 probe
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
    set_property port_width 1               [get_debug_ports u_ila_0/probe1]
    connect_debug_port u_ila_0/probe1 [get_nets {dbg_fault_valid}]

    ## probe2 — dbg_nia[31:0]
    create_debug_port u_ila_0 probe
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
    set_property port_width 32              [get_debug_ports u_ila_0/probe2]
    connect_debug_port u_ila_0/probe2 [lsort -dictionary [get_nets {dbg_nia[*]}]]

    ## probe3 — dbg_fault[31:0]
    create_debug_port u_ila_0 probe
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
    set_property port_width 32              [get_debug_ports u_ila_0/probe3]
    connect_debug_port u_ila_0/probe3 [lsort -dictionary [get_nets {dbg_fault[*]}]]

    ## probe4 — led[1:0]  (led0 = D1/G21, led1 = D2/G20)
    create_debug_port u_ila_0 probe
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
    set_property port_width 2               [get_debug_ports u_ila_0/probe4]
    connect_debug_port u_ila_0/probe4 [lsort -dictionary [get_nets {led0 led1}]]

    implement_debug_core
    close_design
    puts "ILA debug core inserted — Hardware Manager will show 5 named probes."
} else {
    puts "ILA skipped (INSERT_ILA=0 or BASIC license). Building plain bitstream."
}

## ── Implementation ───────────────────────────────────────────────────────
puts "\n═══ Implementation starting (may take 10–25 min) ═══"
launch_runs impl_1 -jobs ${JOBS}
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    set log [glob -nocomplain ${PROJ_DIR}/${TOP}.runs/impl_1/*.log]
    error "Implementation FAILED — check: $log"
}
puts "Implementation complete."

## ── Timing gate ──────────────────────────────────────────────────────────────
## A negative WNS means setup timing is violated — the bitstream will produce
## intermittent or completely wrong behaviour on the real board.  The build
## therefore fails here rather than silently producing a broken bitstream.
##
## Override (emergency / research only):
##   vivado -mode batch -source wukong_xc7a100t.tcl -tclargs --allow-timing-violations
set allow_timing_violations 0
if {[lsearch -exact $argv "--allow-timing-violations"] >= 0} {
    set allow_timing_violations 1
}

set wns [get_property STATS.WNS [get_runs impl_1]]
if {$wns ne "" && $wns < 0} {
    if {$allow_timing_violations} {
        puts "WARNING: Timing violation — WNS = ${wns} ns."
        puts "WARNING: --allow-timing-violations was set; continuing with a broken bitstream."
        puts "WARNING: DO NOT use this bitstream on production hardware."
    } else {
        error "TIMING FAILURE: WNS = ${wns} ns (negative means setup violations exist).\nThis bitstream would behave incorrectly on real hardware and has NOT been written.\nFix the timing or pass --allow-timing-violations to override (not recommended)."
    }
} else {
    puts "Timing clean (WNS = ${wns} ns)."
}

## ── Bitstream generation ─────────────────────────────────────────────────
puts "\n═══ Generating bitstream ═══"
launch_runs impl_1 -to_step write_bitstream -jobs ${JOBS}
wait_on_run impl_1

## Copy bitstream to working directory for easy access
set bit_src "${PROJ_DIR}/${TOP}.runs/impl_1/${TOP}.bit"
if {[file exists $bit_src]} {
    file copy -force $bit_src ${TOP}.bit
    puts "\n═══════════════════════════════════════════════════════════════════"
    puts " Bitstream ready: [pwd]/${TOP}.bit"
    puts "═══════════════════════════════════════════════════════════════════"

    if {$INSERT_ILA} {
        ## Write ILA probe file — Hardware Manager uses this to map raw probe
        ## indices back to the names declared in the TCL (dbg_boot_complete, etc.)
        ## Load it in Hardware Manager: Program Device → ... → Probes File → select .ltx
        open_run impl_1 -name impl_1
        write_debug_probes -force ${TOP}.ltx
        close_design
        puts " ILA probes file: [pwd]/${TOP}.ltx"
        puts "═══════════════════════════════════════════════════════════════════"
        puts ""
        puts " To program via Vivado Hardware Manager (Tcl console):"
        puts "   open_hw_manager"
        puts "   connect_hw_server -allow_non_jtag"
        puts "   open_hw_target"
        puts "   set_property PROGRAM.FILE {[pwd]/${TOP}.bit} \[lindex \[get_hw_devices\] 0\]"
        puts "   set_property PROBES.FILE  {[pwd]/${TOP}.ltx} \[lindex \[get_hw_devices\] 0\]"
        puts "   program_hw_devices \[lindex \[get_hw_devices\] 0\]"
    } else {
        puts ""
        puts " To program via Vivado Hardware Manager (Tcl console):"
        puts "   open_hw_manager"
        puts "   connect_hw_server -allow_non_jtag"
        puts "   open_hw_target"
        puts "   set_property PROGRAM.FILE {[pwd]/${TOP}.bit} \[lindex \[get_hw_devices\] 0\]"
        puts "   program_hw_devices \[lindex \[get_hw_devices\] 0\]"
    }
    puts ""
    puts " Expected LED behaviour after programming:"
    puts "   D1 (G21):  solid ON during boot (~50 cycles), then blinks ~1 Hz (CM MMIO-controlled)"
    puts "   D2 (G20):  1 Hz heartbeat during boot, then OFF when running (lit = fault latched)"
    puts "   UART E3:   0xBB sentinel byte at 57600 baud within ~1 s of power-on"
    if {$INSERT_ILA} {
        puts ""
        puts " ILA dashboard (Hardware Manager):"
        puts "   Trigger on probe1 (dbg_fault_valid) = 1 to capture any CM fault."
        puts "   Trigger on probe0 (dbg_boot_complete) rising edge to capture boot moment."
    }
    puts "═══════════════════════════════════════════════════════════════════"
} else {
    error "Bitstream not found at $bit_src — check implementation logs."
}

## ── SPI flash image (MCS) ────────────────────────────────────────────────────
## Produces church_wukong_xc7a100t.mcs for programming the on-board SPI NOR flash.
##
## Flash device (QMTECH Wukong V3): Micron N25Q064 (hardware-confirmed)
##   Capacity : 64 Mb (8 MB)
##   Interface: SPI x1 / x2 / x4 (Quad SPI)
##   Voltage  : 3.3 V
##   Vivado part string: n25q64-3.3v-spi-x1_x2_x4
##     (verify with: get_cfgmem_parts *n25q64* in Vivado Tcl console)
## NOTE: Vivado will report "Part selected w25q256jvq, but part n25q64-3.3v detected"
##       if you accidentally select a w25q256 part — the chip is always n25q64.
##
## After programming the flash and pressing the reset button the Church Machine
## boots automatically without re-programming the SRAM.
set mcs_file "[pwd]/${TOP}.mcs"
puts "\n═══ Generating SPI flash image (MCS) ═══"
write_cfgmem \
    -format       mcs       \
    -size         64        \
    -interface    SPIx4     \
    -loadbit      "up 0x0 [pwd]/${TOP}.bit" \
    -file         ${mcs_file} \
    -force
puts "\n═══════════════════════════════════════════════════════════════════"
puts " SPI flash image ready: ${mcs_file}"
puts "═══════════════════════════════════════════════════════════════════"
puts ""
puts " To program the SPI flash via Vivado Hardware Manager (Tcl console):"
puts "   # -- open connection (same as SRAM programming) --"
puts "   open_hw_manager"
puts "   connect_hw_server -allow_non_jtag"
puts "   open_hw_target"
puts "   set device \[lindex \[get_hw_devices\] 0\]"
puts "   refresh_hw_device -update_hw_probes false \$device"
puts ""
puts "   # -- attach flash and program it --"
puts "   create_hw_cfgmem -hw_device \$device \\"
puts "       \[lindex \[get_cfgmem_parts {n25q64-3.3v-spi-x1_x2_x4}\] 0\]"
puts "   set cfgmem \[get_property PROGRAM.HW_CFGMEM \$device\]"
puts "   set_property PROGRAM.BLANK_CHECK  0          \$cfgmem"
puts "   set_property PROGRAM.ERASE        1          \$cfgmem"
puts "   set_property PROGRAM.CFG_PROGRAM  1          \$cfgmem"
puts "   set_property PROGRAM.VERIFY       1          \$cfgmem"
puts "   set_property PROGRAM.FILES        \[list {${mcs_file}}\] \$cfgmem"
puts "   program_hw_cfgmem \$cfgmem"
puts "   boot_hw_device \$device"
puts ""
puts " After programming completes, press the RESET button on the Wukong board."
puts " The Church Machine will boot automatically (no re-programming needed)."
puts "═══════════════════════════════════════════════════════════════════"
