# zynq_xc7z010.tcl — Vivado project creation script for Church Machine
#
# Usage (from project root):
#   vivado -mode batch -source hardware/zynq_xc7z010.tcl
#
# Requires:
#   build/church_zynq_xc7z010.v  (generated by gen_verilog.py zynq)
#   hardware/zynq_xc7z010.xdc
#
# Output: vivado_zynq/church_zynq_xc7z010.bit

set PROJ_NAME church_zynq_xc7z010
set PART      xc7z010clg400-1
set OUTDIR    vivado_zynq
set TOPV      build/church_zynq_xc7z010.v
set XDC       hardware/zynq_xc7z010.xdc

file mkdir $OUTDIR

create_project $PROJ_NAME $OUTDIR -part $PART -force

add_files -norecurse $TOPV
add_files -fileset constrs_1 -norecurse $XDC

set_property top top [current_fileset]

# MMCM primitive: 50 MHz in → 100 MHz out
# The Amaranth Verilog uses clk_in as the raw oscillator input.
# Vivado infers the MMCM from the create_clock + MMCM primitive instantiated
# in the design.  The XDC create_clock on clk_in provides the input constraint;
# the MMCM output clock (CLKOUT0) at 10 ns is set automatically by Vivado
# during synthesis when CLKOUT0_PERIOD=10.0 is present in the MMCM instance.
#
# Only the Zynq PL is used — no PS block, no AXI, no DDR3.

launch_runs synth_1 -jobs 4
wait_on_run synth_1

launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

set BIT $OUTDIR/$PROJ_NAME.runs/impl_1/top.bit
if {[file exists $BIT]} {
    file copy -force $BIT $OUTDIR/${PROJ_NAME}.bit
    puts "\n=== Bitstream written: $OUTDIR/${PROJ_NAME}.bit ==="
} else {
    puts "\n=== ERROR: bitstream not found at $BIT ==="
    exit 1
}

close_project
