# QMTECH ZYJZGW Zynq XC7Z010 — Vivado XDC Constraints
# Church Machine top-level: ChurchZynqXC7Z010
#
# Toolchain: Vivado 2020.x+
# Top module: top  (generated by Amaranth gen_verilog)
# Part: xc7z010clg400-1
#
# Pin reference: QMTECH ZYJZGW schematic (Zynq XC7Z010CLG400)
#
# IMPORTANT: Only the PL (programmable logic) side is used.
# The Zynq PS (ARM cores) is held in reset and not connected.
#
# NOTE ON PIN ASSIGNMENTS: The pins below are based on the typical QMTECH
# XC7Z010 (ZYJZGW) board design.  VERIFY each assignment against your
# specific board revision schematic before programming.  If a pin differs,
# update this file and re-run implementation.
# --------------------------------------------------------------------------

# ── Clock ──────────────────────────────────────────────────────────────────
# 50 MHz PL oscillator.  The QMTECH ZYJZGW routes a 50 MHz crystal oscillator
# to PL pin H16 (bank 35, LVCMOS33).  Vivado will infer the MMCM from the
# create_clock constraint plus the MMCM primitive instantiated by the design.
# VERIFY: confirm oscillator pin against your schematic revision.
set_property PACKAGE_PIN H16 [get_ports clk_in]
set_property IOSTANDARD  LVCMOS33 [get_ports clk_in]
create_clock -period 20.000 -name clk_in [get_ports clk_in]

# ── UART (PMOD JA connector, pins 1/2 — 3.3 V) ────────────────────────────
# Connect an external USB-UART adapter: TX board→host, RX host→board.
# The QMTECH ZYJZGW PMOD JA is typically on bank 35 (3.3 V).
# VERIFY: JA pin 1 (TX) and pin 2 (RX) against your schematic.
set_property PACKAGE_PIN L15 [get_ports uart_tx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_tx]

set_property PACKAGE_PIN L16 [get_ports uart_rx]
set_property IOSTANDARD  LVCMOS33 [get_ports uart_rx]

# ── User LEDs (active-LOW — drive low to illuminate) ──────────────────────
# QMTECH ZYJZGW has 4 user LEDs on the PL side (bank 35, LVCMOS33).
# The Amaranth logic drives led[i]=1 to mean ON; the XDC inversion is done
# via the design logic (active-low convention matches Wukong).
# VERIFY: LED pin assignments against your schematic.
set_property PACKAGE_PIN M14 [get_ports {led[0]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN M15 [get_ports {led[1]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN G14 [get_ports {led[2]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN D18 [get_ports {led[3]}]
set_property IOSTANDARD  LVCMOS33 [get_ports {led[3]}]

# Drive strength and slew for LEDs
set_property DRIVE 8 [get_ports {led[*]}]
set_property SLEW  SLOW [get_ports {led[*]}]

# ── Push button KEY1 (active-LOW, internal pull-up) ───────────────────────
# QMTECH ZYJZGW user push button on PL side (bank 35, LVCMOS33).
# VERIFY: push button pin against your schematic.
set_property PACKAGE_PIN R18 [get_ports push_button]
set_property IOSTANDARD  LVCMOS33 [get_ports push_button]
set_property PULLUP true [get_ports push_button]

# ── Timing constraints ─────────────────────────────────────────────────────
# 100 MHz system clock generated by MMCM from 50 MHz clk_in.
# The MMCM output constraint is set automatically by Vivado when the MMCM
# primitive is instantiated with CLKOUT0_PERIOD=10.0 (see zynq_xc7z010.tcl).
# Input/output false paths for UART and LEDs (slow async paths):
set_false_path -to [get_ports {uart_tx led[*]}]
set_false_path -from [get_ports {uart_rx push_button}]

# ── Configuration ──────────────────────────────────────────────────────────
# Zynq PL configuration voltage bank.
set_property CFGBVS         VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3  [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
