#!/usr/bin/env bash
# scripts/build_ti60_bitstream.sh
#
# Single-command Ti60 F225 bitstream build pipeline.
# Runs: firmware compile → patch_sapphire_init.py → efx_map → efx_pnr → efx_pgm
# → copies output to bitstreams/church_ti60_f225.hex and writes a metadata sidecar.
#
# Usage (from repo root):
#   bash scripts/build_ti60_bitstream.sh
#   bash scripts/build_ti60_bitstream.sh --flash          # also flash + smoke-test
#
# Prerequisites:
#   Efinity 2026.1 (synthesis + P&R + pgm) — $EFINITY_MAP_HOME / $EFINITY_HOME  or ~/efinity/2026.1
#   Efinity RISC-V IDE 2025.2   — toolchain at ~/efinity/efinity-riscv-ide-2025.2/toolchain/bin
#   openFPGALoader               — /usr/bin/openFPGALoader  (apt)  OR  ~/oss-cad-suite/bin/openFPGALoader
#   pyserial                     — pip install pyserial (for smoke-test when --flash is used)
#
# Notes:
#   • script must be run from the repo root (not from hardware/soc_combined/).
#   • Efinity synthesis project lives in ~/church_project/SoC/ (the actual Efinity
#     project directory).  The repo hardware/soc_combined/ sources are the master;
#     they must already be in sync before running this script.
#   • sapphire.v and the symbol .bin files must be present in hardware/soc_combined/
#     (copied from Efinix IP and generated by the firmware build).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOC_DIR="${SOC_PROJECT_DIR:-$HOME/church_project/SoC}"
EFINITY_MAP="${EFINITY_MAP_HOME:-$HOME/efinity/2026.1}"
EFINITY="${EFINITY_HOME:-$HOME/efinity/2026.1}"
BITSTREAMS="$REPO_ROOT/bitstreams"
HW="$REPO_ROOT/hardware/soc_combined"
SCRIPTS="$REPO_ROOT/scripts"
DO_FLASH=0

for _arg in "$@"; do
    case "$_arg" in
        --flash) DO_FLASH=1 ;;
        *) echo "Unknown flag: $_arg" >&2; exit 1 ;;
    esac
done

# ── colour helpers ──────────────────────────────────────────────────────────
_ok()   { printf '\033[0;32m[OK]\033[0m  %s\n' "$*"; }
_info() { printf '\033[0;36m[..]\033[0m  %s\n' "$*"; }
_fail() { printf '\033[0;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }
_warn() { printf '\033[0;33m[WARN]\033[0m %s\n' "$*"; }

_SCRIPT_COMMIT="$(cd "$REPO_ROOT" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
_SCRIPT_DATE="$(cd "$REPO_ROOT" && git log -1 --format=%cd --date=short 2>/dev/null || echo unknown)"
_SCRIPT_DIRTY=""
if [ "$_SCRIPT_COMMIT" != "unknown" ] && ! (cd "$REPO_ROOT" && git diff --quiet -- scripts/build_ti60_bitstream.sh scripts/check_sapphire_patch_fresh.sh 2>/dev/null); then
    _SCRIPT_DIRTY=" (LOCAL UNCOMMITTED CHANGES to build scripts!)"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Ti60 F225 Bitstream Build Pipeline"
echo "  Repo:    $REPO_ROOT"
echo "  SoC dir: $SOC_DIR"
echo "  Commit:  ${_SCRIPT_COMMIT} (${_SCRIPT_DATE})${_SCRIPT_DIRTY}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  If the Commit line above doesn't match what you expect, run 'git pull'"
echo "  in $REPO_ROOT before filing a bug — every guard failure below is only"
echo "  meaningful if this script itself is up to date."
echo ""

# ── Step 0: Pre-flight checks ──────────────────────────────────────────────
_info "Step 0/8: Pre-flight checks"

if [ ! -x "$EFINITY_MAP/bin/efx_map" ]; then
    _fail "Efinity 2026.1 (efx_map) not found at $EFINITY_MAP/bin/efx_map
       Install Efinity 2026.1 or set EFINITY_MAP_HOME to override."
fi

if [ ! -x "$EFINITY/bin/efx_pnr" ]; then
    _fail "Efinity 2026.1 (efx_pnr) not found at $EFINITY/bin/efx_pnr
       Install Efinity 2026.1 or set EFINITY_HOME to override."
fi

if [ ! -d "$SOC_DIR" ]; then
    _fail "SoC project directory not found: $SOC_DIR
       Create it with: cp -r hardware/soc_combined ~/church_project/SoC
       or set SOC_PROJECT_DIR to override."
fi

SAPPHIRE_V="$HW/sapphire.v"
if [ ! -f "$SAPPHIRE_V" ]; then
    _fail "sapphire.v not found at $SAPPHIRE_V
       Copy it from: ~/efinity/2025.2/ipm/ip/efx_tsemac/fpga/Ti60F225_devkit/ip/sapphire/sapphire.v"
fi

_ok "Pre-flight checks passed"
echo ""

# ── Step 1: Build firmware ──────────────────────────────────────────────────
# Always clean-build: make -C firmware without clean can silently reuse stale
# .elf/.bin (touch main.c is unreliable across git stash/pull cycles) so the
# board ends up running old firmware bytes and shows the wrong FW= version.
_info "Step 1/8: Build SoC firmware"
make -C "$HW/firmware" clean 2>&1 | tail -2
make -C "$HW/firmware" 2>&1 | tee /tmp/build_fw.log | grep -E "gcc|riscv|Wrote|error|Error" | head -20
SYM0="$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin"
if [ ! -f "$SYM0" ]; then
    _fail "Firmware build failed: symbol0.bin not found. Check /tmp/build_fw.log"
fi

# ── Post-compile version gate ────────────────────────────────────────────
# Read the real version straight from the #define lines (never from comments
# or the banner string, which can drift independently of the actual build).
# Then verify the compiled artifact is actually newer than main.c — if make
# silently no-op'd (e.g. clock skew, stale ccache) we would otherwise ship a
# bitstream with old firmware bytes but a fresh-looking version string.
FW_MAIN_C="$HW/firmware/main.c"
FW_MAJOR="$(grep -oE '#define[[:space:]]+FW_MAJOR[[:space:]]+[0-9]+' "$FW_MAIN_C" | grep -oE '[0-9]+$' || echo "")"
FW_MINOR="$(grep -oE '#define[[:space:]]+FW_MINOR[[:space:]]+[0-9]+' "$FW_MAIN_C" | grep -oE '[0-9]+$' || echo "")"
if [ -z "$FW_MAJOR" ] || [ -z "$FW_MINOR" ]; then
    _fail "Could not parse FW_MAJOR/FW_MINOR #define lines from $FW_MAIN_C"
fi
FW_VERSION="v${FW_MAJOR}.${FW_MINOR}"

FW_ARTIFACT=""
for _cand in "$HW/firmware/firmware.hex" "$HW/firmware/firmware.elf"; do
    if [ -f "$_cand" ]; then
        FW_ARTIFACT="$_cand"
        break
    fi
done
if [ -z "$FW_ARTIFACT" ]; then
    _fail "Neither firmware.hex nor firmware.elf found after clean+build in $HW/firmware"
fi
if [ "$FW_MAIN_C" -nt "$FW_ARTIFACT" ]; then
    _fail "firmware.hex is older than main.c after clean+build — aborting"
fi
_ok "Firmware ${FW_VERSION} compiled"

# Show the firmware banner string that was compiled in (informational only)
FW_BANNER=$(python3 -c "
import re, pathlib
mc = pathlib.Path('$HW/firmware/main.c').read_text()
m = re.search(r'uart_puts\(\"([^\"]+)\"', mc)
print(m.group(1).strip() if m else 'unknown')
" 2>/dev/null || echo "unknown")
_ok "Firmware built — banner: $FW_BANNER  symbol files in $HW/"
echo ""

# ── Step 1.5: Sync firmware source into the Efinity project directory ───────
# $SOC_DIR (the Efinity synthesis project, e.g. ~/church_project/SoC) has
# historically drifted from the repo's hardware/soc_combined/firmware/ — a
# stale, untracked copy sitting there let run_efx_map.sh's old firmware
# rebuild step silently bake old firmware bytes into the bitstream even
# though this script had already built and patched the correct version.
# That rebuild step no longer exists (see run_efx_map.sh), but we still
# mirror the repo firmware into $SOC_DIR so there is only ever ONE firmware
# source on disk during a build — eliminating the divergence by construction
# rather than relying on every script remembering to read from the right
# place.
_info "Step 1.5/8: Sync firmware source into $SOC_DIR/firmware"
mkdir -p "$SOC_DIR/firmware"
rsync -a --delete "$HW/firmware/" "$SOC_DIR/firmware/"
if ! bash "$SCRIPTS/check_firmware_sha_sync.sh" "$HW/firmware" "$SOC_DIR/firmware"; then
    _fail "Firmware sync verification failed — $SOC_DIR/firmware still differs from $HW/firmware after rsync (see sha256 guard output above)"
fi
_ok "Firmware source synced and verified byte-identical: $SOC_DIR/firmware"
echo ""

# ── Step 2: Patch sapphire.v ────────────────────────────────────────────────
# patch_sapphire_init.py writes firmware BRAM init-data into the repo copy
# ($HW/sapphire.v).  After patching we MUST also copy it to $SOC_DIR because
# Efinity's church_soc_cm.xml references sapphire.v relative to the project
# directory (~/church_project/SoC/), NOT the repo directory.  Without this
# copy step synthesis silently re-uses the old version from $SOC_DIR and
# the flashed bitstream carries the previous firmware version.
_info "Step 2/8: Patch sapphire.v (embed firmware into BRAM init blocks)"
python3 "$SCRIPTS/patch_sapphire_init.py" \
    "$SAPPHIRE_V" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol0.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol1.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol2.bin" \
    "$HW/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol3.bin"
_ok "sapphire.v patched (repo copy: $SAPPHIRE_V)"
# Deploy patched sapphire.v to the Efinity project directory
cp "$SAPPHIRE_V" "$SOC_DIR/sapphire.v"
_ok "sapphire.v deployed to $SOC_DIR/sapphire.v"

# sapphire.v only contains $readmemb("<bare filename>", ram_symbolN) calls —
# the actual bin *contents* still have to be found on disk by EFX_MAP at
# synthesis time. EFX_MAP resolves those bare filenames relative to
# --work_dir (work_syn/), NOT hardware/soc_combined/ and NOT $SOC_DIR itself
# (see .agents/memory/efx-map-readmemb.md — empirically confirmed). Deploying
# sapphire.v without also deploying the bins into $SOC_DIR/work_syn/ leaves
# whatever bins (possibly stale, possibly none) already happen to be sitting
# there, which MAP will silently embed with no error.
mkdir -p "$SOC_DIR/work_syn"
cp "$HW"/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol*.bin "$SOC_DIR/work_syn/"
if ! bash "$SCRIPTS/check_sapphire_symbol_bins_fresh.sh" "$HW" "$SOC_DIR/work_syn"; then
    _fail "Sapphire symbol bins in $SOC_DIR/work_syn are stale after copy — see guard output above"
fi
_ok "Sapphire symbol bins deployed to $SOC_DIR/work_syn/ and verified fresh"
echo ""

# ── Step 2.5: Copy CM Verilog and peri.xml to SoC project ───────────────────
# build/church_ti60_f225.v has 16K dmem[] entries but ~99% are zero.
# Zero assignments are stripped at commit time → only ~93 non-zero lines remain.
# This makes EFX_MAP synthesis 20–50× faster and prevents OOM hangs on
# resource-limited machines.  The stripped copy is kept in build/ (canonical);
# here we deploy it into the Efinity project directory before synthesis runs.
#
# church_soc_cm.peri.xml MUST also be deployed: top.v top-level ports (e.g.
# cm_uart_rx) must have matching GPIO entries in peri.xml or efx_map crashes
# with a bare STACK TRACE before printing any synthesis output.
_info "Step 2.5/8: Deploy CM Verilog to SoC project"
CM_V_SRC="$REPO_ROOT/build/church_ti60_f225.v"
CM_V_DST="$SOC_DIR/church_ti60_f225.v"
if [ ! -f "$CM_V_SRC" ]; then
    _fail "church_ti60_f225.v not found at $CM_V_SRC — regenerate with hardware/gen_verilog.py"
fi
cp "$CM_V_SRC" "$CM_V_DST"
# Yosys flattens the Amaranth design into 'module top'; top.v instantiates
# 'church_ti60f225' (no underscore).  Rename so there is no duplicate 'top'.
sed -i 's/^module top(/module church_ti60f225(/' "$CM_V_DST"
NON_ZERO=$(grep -c "dmem\[" "$CM_V_DST" || true)
_ok "church_ti60_f225.v deployed ($NON_ZERO non-zero dmem[] lines)"

# ── gen_cm_dmem_direct: replace inferred dmem with explicit EFX_RAM10 ────────
# EFX_MAP 2026.1 silently drops ALL forms of BRAM init for inferred arrays:
#   • initial begin        → BRAM all-zero after synthesis
#   • $readmemb/$readmemh  → INIT stored in defparam only; efx_pnr reads
#                            verific comments (no INIT_N there) → still zero
# The ONLY working path: explicit EFX_RAM10 instantiation with inline INIT params.
# gen_cm_dmem_direct.py:
#   1. Reads boot ROM words from church_ti60_f225.v's initial begin block
#   2. Writes cm_dmem_bram.v — 64 explicit EFX_RAM10 instances with INIT values
#   3. Patches church_ti60_f225.v to instantiate cm_dmem_bram instead of dmem[]
# cm_dmem_bram.v is listed in church_soc_cm.xml (deployed immediately below).
GEN_CM_DMEM="$HW/gen_cm_dmem_direct.py"
if [ ! -f "$GEN_CM_DMEM" ]; then
    _fail "gen_cm_dmem_direct.py not found at $GEN_CM_DMEM"
fi
python3 "$GEN_CM_DMEM" "$SOC_DIR" 2>&1 | grep -E "Written|Replaced|Patched|already|ERROR|cm_dmem|non-zero"
if grep -q 'cm_dmem_bram' "$CM_V_DST" 2>/dev/null; then
    _ok "church_ti60_f225.v CM BRAM → explicit EFX_RAM10 (cm_dmem_bram)"
else
    _warn "gen_cm_dmem_direct.py did not patch church_ti60_f225.v — check output above"
fi

# Deploy church_soc_cm.xml from repo (ensures cm_dmem_bram.v is listed as a source).
# The sed at Step 3 strips any banned params from the freshly-deployed copy.
XML_SRC="$HW/church_soc_cm.xml"
XML_DST="$SOC_DIR/church_soc_cm.xml"
if [ -f "$XML_SRC" ]; then
    cp "$XML_SRC" "$XML_DST"
    _ok "church_soc_cm.xml deployed (source list includes cm_dmem_bram.v)"
else
    _warn "church_soc_cm.xml not found at $XML_SRC — using existing SoC copy"
fi

PERI_SRC="$HW/church_soc_cm.peri.xml"
PERI_DST="$SOC_DIR/church_soc_cm.peri.xml"
if [ -f "$PERI_SRC" ]; then
    cp "$PERI_SRC" "$PERI_DST"
    _ok "church_soc_cm.peri.xml deployed (IO pin definitions)"
else
    _warn "church_soc_cm.peri.xml not found at $PERI_SRC — skipping (existing SoC copy will be used)"
fi

# Deploy top.v and apb3_cm_bridge.v from repo.
#
# CRITICAL: these files are NOT auto-deployed by Efinity or any other step —
# synthesis uses whatever copy already exists in $SOC_DIR.  A stale top.v
# with jtagCtrl_reset(1'b0) keeps the debug clock domain in permanent reset,
# which propagates to io_systemReset → system_reset stays HIGH → LED0 OFF,
# UART silent, SoC never runs firmware.  This was the root cause of the
# Jul 2026 "board says nothing" incident (green FPGA-configured LED on,
# all 3 user LEDs off).  Always deploy both files so the bitstream matches
# the repo.
TOP_V_SRC="$HW/top.v"
TOP_V_DST="$SOC_DIR/top.v"
if [ -f "$TOP_V_SRC" ]; then
    cp "$TOP_V_SRC" "$TOP_V_DST"
    _ok "top.v deployed from repo"
    if grep -qE "jtagCtrl_reset[[:space:]]*\([[:space:]]*1'b1" "$TOP_V_DST"; then
        _ok "top.v: jtagCtrl_reset=1'b1 confirmed (SoC will not be stuck in reset)"
    else
        _fail "top.v: jtagCtrl_reset is NOT 1'b1 — SoC would stay in permanent reset (LED0 OFF, UART silent). Fix hardware/soc_combined/top.v before proceeding."
    fi
else
    _fail "top.v not found at $TOP_V_SRC — cannot deploy to $SOC_DIR. Check hardware/soc_combined/."
fi

APB3_SRC="$HW/apb3_cm_bridge.v"
APB3_DST="$SOC_DIR/apb3_cm_bridge.v"
if [ -f "$APB3_SRC" ]; then
    cp "$APB3_SRC" "$APB3_DST"
    _ok "apb3_cm_bridge.v deployed from repo"
else
    _warn "apb3_cm_bridge.v not found at $APB3_SRC — using existing SoC copy (may be stale)"
fi
echo ""

# ── Pre-synthesis patch guard ────────────────────────────────────────────────
# Content-based sanity check that Step 2 actually left sapphire.v in patched
# form (bare-filename $readmemb block present for all 4 ram_symbol lanes).
# This is NOT an mtime comparison — sapphire.v's $readmemb block text is
# identical across every firmware rebuild (it only references bare filenames,
# never firmware bytes), so patch_sapphire_init.py correctly no-ops once
# already patched and never touches sapphire.v's mtime again. An mtime-based
# guard here would false-positive forever after the first successful patch.
# See check_sapphire_patch_fresh.sh header comment for the full incident.
_info "Pre-synthesis patch guard: verifying sapphire.v is patched"
bash "$SCRIPTS/check_sapphire_patch_fresh.sh" "$SAPPHIRE_V" || {
    _fail "sapphire.v patch is stale — re-run 'python3 scripts/patch_sapphire_init.py' then retry."
}
echo ""

# ── Step 3: Synthesis (EFX_MAP, Efinity 2026.1) ─────────────────────────────
_info "Step 3/8: Synthesis (efx_map — Efinity 2026.1, ~45 min)"

# Force fresh synthesis by deleting any cached VDB.
#
# EFX_MAP decides whether to re-synthesise by comparing Verilog source file
# mtimes against the existing VDB.  The Sapphire ROM firmware lives in four
# .bin files (symbol0..3) that are referenced via $readmemb in sapphire.v.
# sapphire.v's OWN mtime does not change when the .bin files are updated
# (patch_sapphire_init.py is idempotent after the first patch, by design —
# see scripts/check_sapphire_patch_fresh.sh header for the full history).
# MAP therefore sees "Verilog unchanged, VDB is fresh" and exits in seconds
# while quietly baking the OLD firmware bytes into the new bitstream.
#
# Deleting the VDB forces MAP to run a full synthesis pass (the expected
# 30–45 min) and re-read the .bin files from work_syn/ on every build.
# This is the correct trade-off: the alternative is firmware that never
# changes on the board no matter how many times you rebuild.
for _vdb in \
    "$SOC_DIR/outflow/church_soc_cm.vdb" \
    "$SOC_DIR/work_syn/church_soc_cm.vdb" \
    "$SOC_DIR/outflow/top.vdb" \
    "$SOC_DIR/work_syn/top.vdb"; do
    if [ -f "$_vdb" ]; then
        rm -f "$_vdb"
        _ok "Removed stale VDB cache: $_vdb"
    fi
done
_ok "VDB cache cleared — MAP will perform full synthesis (reads fresh firmware .bin files)"
echo ""

# Efinity GUI re-injects infer_set_reset / infer_clk_enable into the local
# project XML whenever the project is opened.  These params crash efx_map
# (hard STACK TRACE exit) on 2025.2.  Strip them every time before synthesis.
sed -i \
    -e '/<efx:param name="infer_set_reset"/d' \
    -e '/<efx:param name="infer_clk_enable"/d' \
    "$SOC_DIR/church_soc_cm.xml"

# Sentinel so run_efx_map.sh knows it was invoked via the One Button Build
# Script (and therefore make clean / patch_sapphire_init.py / gen_cm_dmem_direct.py
# have already run) and can suppress its direct-invocation warning.
export _OBBS_RUN=1
EFINITY_HOME="$EFINITY_MAP" bash "$HW/run_efx_map.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_map.log | tail -8

# Derive circuit name from the project XML filename — same convention used by
# run_efx_pnr.sh and run_efx_pgm.sh.  This never requires map.v to exist.
CIRCUIT="$(basename "$SOC_DIR/church_soc_cm.xml" .xml)"
_ok "  Circuit: $CIRCUIT"

# Post-synthesis INIT_0 guard — must pass before P&R starts.
# Efinity 2025.2/2026.1 sometimes writes map.v to outflow/, sometimes work_syn/.
# If map.v is not found, skip with a warning (the guard cannot run but P&R will
# fail fast on its own if synthesis actually produced missing output).
MAP_V="$(find "$SOC_DIR/outflow" "$SOC_DIR/work_syn" -maxdepth 3 -name "*.map.v" 2>/dev/null | head -1)"
if [ -z "$MAP_V" ] || [ ! -f "$MAP_V" ]; then
    _warn "  map.v not found under $SOC_DIR/outflow or work_syn — skipping BRAM INIT_0 guard"
    _warn "  (This is normal for some Efinity 2025.2 project layouts.)"
    _warn "  P&R will proceed; it will fail if synthesis output is missing."
else
    _ok "  map.v: $MAP_V"
    _info "  Running post-synthesis BRAM INIT_0 guard..."
    BRAM_GUARD_RC=0
    bash "$SCRIPTS/check_bram_init_zero.sh" "$MAP_V" "$SOC_DIR/work_syn" || BRAM_GUARD_RC=$?
    if [ "$BRAM_GUARD_RC" -eq 1 ]; then
        _fail "BRAM INIT_0 guard failed — all lanes zero. Aborting before P&R.
  Run: python3 scripts/patch_sapphire_init.py"
    elif [ "$BRAM_GUARD_RC" -eq 2 ]; then
        _warn "  BRAM INIT_0 guard returned inconclusive (instance names differ) — continuing."
        _warn "  Verify BRAM manually after P&R: grep INIT_0 $MAP_V | grep ram_symbol | head -4"
    elif [ "$BRAM_GUARD_RC" -eq 3 ]; then
        _fail "BRAM content mismatch — synthesis embedded a DIFFERENT firmware version than compiled.
  Stale symbol files in $SOC_DIR/work_syn/ were used by MAP.
  Fix: delete work_syn/*.bin, rebuild firmware, re-copy symbol bins, delete VDB, retry."
    else
        _ok "All 4 BRAM INIT_0 lanes non-zero and content matches compiled firmware"
    fi
fi
echo ""

# ── Step 3b: Deploy symbol bins to PNR search paths ─────────────────────────
# EFX_MAP keeps $readmemb as a bare-filename reference in map.v (does NOT
# inline data into INIT_0).  EFX_PNR must resolve those bare filenames at
# P&R time from its own working directory.  Efinity 2026.1 searches at least
# three locations: work_pnr/, the project root (SOC_DIR/), and outflow/.
# We already deployed to work_syn/ above; copy to the remaining candidates
# so PNR always finds them regardless of internal CWD changes.
mkdir -p "$SOC_DIR/work_pnr"
cp "$HW"/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol*.bin "$SOC_DIR/work_pnr/"
cp "$HW"/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol*.bin "$SOC_DIR/"
mkdir -p "$SOC_DIR/outflow"
cp "$HW"/EfxSapphireSoc.v_toplevel_system_ramA_logic_ram_symbol*.bin "$SOC_DIR/outflow/"
_ok "Sapphire symbol bins deployed to work_pnr/, project root, and outflow/ (PNR \$readmemb paths)"
echo ""

# ── Step 4: Place & Route (EFX_PNR, Efinity 2026.1) ────────────────────────
_info "Step 4/8: Place & Route (efx_pnr — Efinity 2026.1, ~5 min)"
# tail -30 (not -8): run_efx_pnr.sh's Interface Designer failure path now
# ends with a multi-line interface.log error digest that must survive this
# truncation — an -8 tail previously hid the real crash reason, leaving only
# the generic "did not provide ... .interface.csv" line visible.
bash "$HW/run_efx_pnr.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pnr.log | tail -30
LBF="$SOC_DIR/work_pnr/${CIRCUIT}.lbf"
if [ ! -f "$LBF" ]; then
    _fail "P&R output not found: $LBF — P&R may have failed. Check /tmp/build_pnr.log"
fi
_ok "Place & Route complete"
echo ""

# ── Step 5: Generate SPI flash hex (efx_pgm) ────────────────────────────────
_info "Step 5/8: Generate SPI flash hex (efx_pgm, ~30 s)"
bash "$HW/run_efx_pgm.sh" "$SOC_DIR/church_soc_cm.xml" 2>&1 | tee /tmp/build_pgm.log | tail -5
HEX_SRC="$SOC_DIR/outflow/${CIRCUIT}.hex"
if [ ! -f "$HEX_SRC" ]; then
    _fail "Hex output not found: $HEX_SRC — efx_pgm may have failed. Check /tmp/build_pgm.log"
fi
_ok "Hex generated: $HEX_SRC ($(du -h "$HEX_SRC" | cut -f1))"
echo ""

# ── Step 6: Copy to bitstreams/ ─────────────────────────────────────────────
_info "Step 6/8: Copy output to $BITSTREAMS/"
mkdir -p "$BITSTREAMS"
cp "$HEX_SRC" "$BITSTREAMS/church_ti60_f225.hex"
if [ -f "$SOC_DIR/outflow/${CIRCUIT}.bit" ]; then
    cp "$SOC_DIR/outflow/${CIRCUIT}.bit" "$BITSTREAMS/church_ti60_f225.bit"
fi

# Detect firmware version directly from the #define FW_MAJOR/FW_MINOR lines —
# never from a comment or banner string, which can drift out of sync with the
# actual compiled defines (see Step 1's post-compile gate for the same read).
FW_VERSION="unknown"
FW_MAIN="$HW/firmware/main.c"
if [ -f "$FW_MAIN" ]; then
    _META_FW_MAJOR="$(grep -oE '#define[[:space:]]+FW_MAJOR[[:space:]]+[0-9]+' "$FW_MAIN" | grep -oE '[0-9]+$' || echo "")"
    _META_FW_MINOR="$(grep -oE '#define[[:space:]]+FW_MINOR[[:space:]]+[0-9]+' "$FW_MAIN" | grep -oE '[0-9]+$' || echo "")"
    if [ -n "$_META_FW_MAJOR" ] && [ -n "$_META_FW_MINOR" ]; then
        FW_VERSION="v${_META_FW_MAJOR}.${_META_FW_MINOR}"
    fi
fi

HEX_SIZE=$(wc -c < "$BITSTREAMS/church_ti60_f225.hex")
BUILT_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "$BITSTREAMS/church_ti60_f225.json" <<ENDJSON
{
  "built_at": "$BUILT_AT",
  "firmware_version": "$FW_VERSION",
  "size_bytes": $HEX_SIZE
}
ENDJSON

_ok "Copied to $BITSTREAMS/church_ti60_f225.hex"
_ok "Metadata written to $BITSTREAMS/church_ti60_f225.json"
echo ""

# ── Step 7: Flash + smoke-test (optional, --flash flag) ─────────────────────
if [ "$DO_FLASH" -eq 1 ]; then
    _info "Step 7/8: Flash board with openFPGALoader"
    # Find openFPGALoader: prefer oss-cad-suite bundle, fall back to system install
    OFLPGM="${OSS_CAD_SUITE:-$HOME/oss-cad-suite}/bin/openFPGALoader"
    if [ ! -x "$OFLPGM" ]; then
        OFLPGM="$(which openFPGALoader 2>/dev/null || true)"
    fi
    if [ -z "$OFLPGM" ] || [ ! -x "$OFLPGM" ]; then
        _warn "openFPGALoader not found — skipping flash."
        _warn "Install with: sudo apt install openFPGALoader   or set OSS_CAD_SUITE."
    else
        sudo "$OFLPGM" -b titanium_ti60_f225_jtag -f "$BITSTREAMS/church_ti60_f225.hex"
        _ok "Flash complete"
        echo ""
        _info "  Waiting 5 s for board to boot..."
        sleep 5
        _info "  Running UART smoke-test (expecting fw=${FW_MAJOR}.${FW_MINOR})..."
        # --expect-fw closes the loop on the stale-firmware bug: it fails
        # loudly right here if the board reports a version other than the
        # one that was just built and flashed, instead of that mismatch
        # only surfacing later as a confusing banner string in the IDE.
        python3 "$SCRIPTS/test_ti60_uart.py" --port=auto --baud=57600 --timeout=30 --verbose \
            --expect-fw="${FW_MAJOR}.${FW_MINOR}"
    fi
else
    _info "Step 7/8: Flash skipped (pass --flash to flash + smoke-test automatically)"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  BUILD COMPLETE"
echo "  Output: $BITSTREAMS/church_ti60_f225.hex"
echo "  Meta:   $BITSTREAMS/church_ti60_f225.json"
echo ""
echo "  Good-build commit ritual:"
echo "    git add bitstreams/"
echo "    git commit -m \"bitstream: Ti60 $(date -u +%Y-%m-%d)\""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
